ITEM_ID_FIELD: item_id
RATING_FIELD: rating
USER_ID_FIELD: user_id
checkpoint_dir: saved/
data_path: dataset/collections/
dataloaders_save_path: dataloader/
epochs: 50
eval_args:
  group_by: user
  mode: pop100
  order: RO
  split:
    RS:
    - 8
    - 1
    - 1
eval_batch_size: 4096
eval_step: 1
field_separator: "\t"
item_inter_num_interval: '[0,inf)'
learner: adam
learning_rate: 0.001
log_wandb: true
loss_decimal_place: 4
metric_decimal_place: 4
metrics:
- Recall
- MRR
- NDCG
- Hit
- MAP
- Precision
- GAUC
reproducibility: true
save_dataloaders: true
save_dataset: false
seed: 2022
seq_separator: ' '
show_progress: true
stopping_step: 3000
topk:
- 1
- 2
- 5
- 10
- 20
train_batch_size: 2048
train_neg_sample_args:
  candidate_num: 0
  distribution: popularity
  dynamic: false
  sample_num: 5
valid_metric: NDCG@20
